### ISSUE TITLE
Update PhotonLib to latest

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-everybot#21]
**Summary**
This project is still using PhotonLib from 2024 beta. There's a new feature update specific to the 2024 season that we should be using instead: https://github.com/PhotonVision/photonvision/releases/tag/v2024.2.0

**Work Scope**
- Update PhotonLib to the latest version

**Comment by linglejack06** [comment]
I will keep an eye out for the vendor dependency update. So far they have only released the photon vision interface update and not photon library for wpi lib. Maven still shows latest source file as 2024.3.1-beta-3.2. (The one currently installed)

**Comment by jkleiber** [comment]
It is likely that since this is currently set to the beta version, it cannot detect updates on the actual 2024 release. 2024-Robot-Code has v2024.1.2 installed (which is also behind the latest release). You may need to reinstall the vendor dependency just to clear out the beta version

**Comment by linglejack06** [comment]
yes that was it, opened pull request to merge update into main
